version: '3'
services:
  afisha_api: 
    build: 
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - '3000:8000'
    depends_on:
      - afisha_db
  
  afisha_db:
    image: 'postgres:14'
    env_file:
      - '.env'
    environment:
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - 'afisha_afisha-data:/var/lib/postgresql/data'
volumes:
  afisha_afisha-data:
    